name: Helm Deploy for d01/s01

on:
  push:
    branches:
      - d01
      - s01
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout current branch (triggered branch)
        uses: actions/checkout@v3

      - name: Checkout centralized config from main
        uses: actions/checkout@v3
        with:
          ref: main
          path: central-config

      - name: Determine ENV name
        id: env
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH" == "d01" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "$BRANCH" == "s01" ]]; then
            echo "env=stage" >> $GITHUB_OUTPUT
          else
            echo "Unknown branch: $BRANCH"
            exit 1
          fi



      - name: Replace $(ENV) in all YAMLs
        run: |
          mkdir rendered
          for file in helm-configs/*.yaml; do
            fname=$(basename "$file")
            sed "s/\\$(ENV)/${{ steps.env.outputs.env }}/g" "$file" > "rendered/$fname"
          done

      - name: Apply with Helm (or dry run first)
        run: |
          for file in rendered/*.yaml; do
            echo "Deploying $file..."
            helm upgrade --install "$(basename "$file" .yaml)" ./charts/yourchart \
              --values "$file" --namespace your-ns --create-namespace
          done

